import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Inter } from "next/font/google";
import { Footer } from "@/components/footer";
import { SessionProvider } from "@/lib/hooks";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-inter",
});

const gilroyBold = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
  variable: "--font-gilroy-bold",
});
const gilroySemibold = localFont({
  src: "./fonts/Gilroy-SemiBold.ttf",
  variable: "--font-gilroy-semibold",
});

const gilroyMedium = localFont({
  src: "./fonts/Gilroy-Medium.ttf",
  variable: "--font-gilroy-medium",
});

const gilroy = localFont({
  src: "./fonts/Gilroy-Regular.ttf",
  variable: "--font-gilroy",
});
const gilroyLight = localFont({
  src: "./fonts/Gilroy-Light.ttf",
  variable: "--font-gilroy-light",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${gilroy.variable} ${gilroyBold.variable} ${gilroyLight.variable} ${gilroyMedium.variable} ${gilroySemibold.variable}`}
    >
      <body className=" bg-white text-black">
        <SessionProvider>
          <div className="font-gilroy">
            <Navbar />
            {children}
            <Footer />
          </div>
          <Toaster richColors position="top-center" duration={2000} />
        </SessionProvider>
      </body>
    </html>
  );
}
